# -*- coding: utf-8 -*-
"""Lab2Tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xkx-ia1jed7OiyX818JZKwyfK_A3-3Pw
"""

#Tuple Questions
11.	Given a tuple my_tuple = (5, 10, 15, 20, 25), how can you access the element 15 using positive indexing? Write a Python program to achieve this.

tp=(5, 10, 15, 20, 25)
print(tp[2])

"""2.	Given a tuple my_tuple = (100, 200, 300, 400, 500), how can you access the element 300 using negative indexing? Write a Python program to achieve this."""

tp=(100, 200, 300, 400, 500)
print(tp[-3])

"""3.	Given a tuple my_tuple = (1, 2, 3, (4, 5, 6)), how can you access the element 6 from the nested tuple using indexing? Write a Python program to achieve this"""

tp= (1, 2, 3, (4, 5, 6))
print(tp[3][2])

"""4.	Given a tuple my_tuple = (5, 10, 15, 20, 25), how can you slice it to obtain (10, 15, 20)? Write a Python program to achieve this."""

tp=(5, 10, 15, 20, 25)
print(tp[1:4])

"""5.	Given a tuple my_tuple = ('Python', 'Java', 'C++', 'JavaScript'), how can you access the last element without knowing its index? Write a Python program to achieve this."""

tp=('Python', 'Java', 'C++', 'JavaScript')
print(tp[-1])

"""6.	Given two tuples tuple1 = (1, 2, 3) and tuple2 = (4, 5, 6), how can you concatenate them into a single tuple? Write a Python program to achieve this."""

tp1=(1, 2, 3)
tp2=(4,5,6)
print(tp1+tp2)

"""7.	Given a tuple my_tuple = ('x', 'y', 'z', 'a'), how can you check if the element 'y' exists in the tuple? Write a Python program to achieve this."""

tp=('x', 'y', 'z', 'a')
print("y" in tp)

"""8.	Given a tuple my_tuple = ('apple', 'banana', 'apple', 'cherry', 'apple'), how can you count the number of occurrences of 'apple'? Write a Python program to achieve this."""

tp= ('apple', 'banana', 'apple', 'cherry', 'apple')
print(tp.count("apple"))

"""9.	Given a tuple my_tuple = (True, False, True, False), how can you find the number of True values in the tuple? Write a Python program to achieve this"""

tp=(True, False, True, False)
print(tp.count(True))

"""10.	Given a tuple my_tuple = ('Python', 3.8, True, (1, 2, 3)), how can you access the nested tuple (1, 2, 3)? Write a Python program to achieve this."""

tp=('Python', 3.8, True, (1, 2, 3))
print(tp[3])

"""11.	Given a tuple my_tuple = (10, 20, 30), how can you convert it into a list? Write a Python program to achieve this."""

tp=(10, 20, 30)
print(list(tp))

"""12.	Given a tuple my_tuple = (7, 14, 21, 28, 35), how can you find the smallest and largest elements? Write a Python program to achieve this."""

tp= (7, 14, 21, 28, 35)
print("Largest value= ",max(tp))
print("Smallest value= ",min(tp))

"""13.	Given a tuple my_tuple = (2, 4, 6, 8, 10), how can you find the sum of all elements? Write a Python program to achieve this."""

tp=(2, 4, 6, 8, 10)
print(sum(tp))

tp=(2, 4, 6, 8, 10)
sum=0
for i in tp:
  sum=sum+i
print(sum)

"""14.	Given a tuple my_tuple = ('a', 'b', 'c', 'd'), how can you reverse the order of elements? Write a Python program to achieve this."""

tp=('a', 'b', 'c', 'd')
rev=""
for i in tp:
  rev=i+rev
print(rev)

"""15.	Given two tuples tuple1 = (1, 2, 3) and tuple2 = (1, 2, 3), how can you check if they are equal? Write a Python program to achieve this."""

tp1=(1,2,3)
tp2=(1,2,3)
print(tp1==tp2)

"""16.	Given a tuple my_tuple = (10, 20, 30, 40), how can you unpack its values into separate variables? Write a Python program to achieve this"""

tp=(10, 20, 30, 40)
a,b,c,d=tp
print(a)
print(b)
print(c)
print(d)

"""17.	Given a tuple my_tuple = (3, 6, 9, 12, 15), how can you convert it into a string? Write a Python program to achieve this."""

tp=(3, 6, 9, 12, 15)
print(str(tp))

tp=(1, 2, 3, 4, 5)
for i in tp:
  print(i)

"""19.	Given a tuple my_tuple = (100, 200, 300, 400), how can you convert it into a dictionary with keys as index positions? Write a Python program to achieve this."""

my_tuple = (100, 200, 300, 400)
result = dict(enumerate(my_tuple))
print(result)

"""20.	Given a tuple my_tuple = (1, 2, 3, 4, 5), how can you delete the entire tuple? Write a Python program to achieve this."""

tp=(1, 2, 3, 4, 5)
del tp