# -*- coding: utf-8 -*-
"""Lab3Set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKti27cJjgo9ok9af7ZoInIgJZt94MxE

Question 1: Given a set my_set = {10, 20, 30, 40, 50}, how can you check if the number 30 exists in the set? Write a Python program to achieve this
"""

my_set = {10, 20, 30, 40, 50}
print(30 in my_set)

"""Question 2: Suppose you have a set my_set = {1, 2, 3, 4, 5}. How can you add the element 6 to this set? Write a Python program to achieve this."""

my_set = {1, 2, 3, 4, 5}
my_set.add(6)
print(my_set)

"""Question 3: Given a set my_set = {10, 20, 30, 40, 50}, how can you remove the element 30 from the set? Write a Python program to achieve this."""

my_set = {10, 20, 30, 40, 50}
my_set.remove(30)
print(my_set)

"""Question 4: Suppose you have two sets: set1 = {1, 2, 3} and set2 = {3, 4, 5}. How can you find their union? Write a Python program to achieve this."""

set1 = {1, 2, 3}
set2={4,5,6}
print(set1.union(set2))

"""Question 5: Given two sets set1 = {10, 20, 30} and set2 = {30, 40, 50}, how can you find their intersection? Write a Python program to achieve this."""

set1 = {10, 20, 30}
set2={30,40,50}
print(set1.intersection(set2))

"""Question 6: Suppose you have two sets: set1 = {10, 20, 30} and set2 = {30, 40, 50}. How can you find elements that are in set1 but not in set2? Write a Python program to achieve this."""

set1 = {10, 20, 30}
set2={30,40,50}
print(set1.difference(set2))

"""Question 7: Given a set my_set = {1, 2, 3}, how can you remove an element randomly from the set? Write a Python program to achieve this."""

my_set = {1, 2, 3}
 my_set.pop()
 print(my_set)

"""Question 9: Given two sets set1 = {1, 2, 3} and set2 = {3, 4, 5}, how can you find the symmetric difference? Write a Python program to achieve this."""

set1 = {1, 2, 3}
set2={3,4,5}
print(set1.symmetric_difference(set2))

"""Question 10: Suppose you have a set my_set = {10, 20, 30, 40, 50}, how can you find the length of the set? Write a Python program to achieve this."""

my_set = {10, 20, 30, 40, 50}
print(len(my_set))

"""Question 11: Given a set set1 = {10, 20, 30} and a frozen set set2 = frozenset({30, 40, 50}), can you modify set2? Write a Python program to explain why."""

set1 = {10, 20, 30}
set2 = frozenset({30, 40, 50})
set2.add(60)   # This will cause an error

"""Question 12: Suppose you have a set my_set = {1, 2, 3}. How can you update it with another set {4, 5, 6}? Write a Python program to achieve this."""

my_set = {1, 2, 3}
new_set = {4, 5, 6}
my_set.update(new_set)
print("Updated set:", my_set)

"""Question 13: Given a set my_set = {'apple', 'banana', 'cherry'}, how can you check if it is a subset of another set { 'apple', 'banana', 'cherry', 'date'}? Write a Python program to achieve this."""

my_set = {'apple', 'banana', 'cherry'}
set2 = {'apple', 'banana', 'cherry', 'date'}
result = my_set.issubset(set2)
print("Is my_set a subset of set2?", result)

"""Question 14: Suppose you have two sets set1 = {1, 2, 3, 4} and set2 = {3, 4}, how can you check if set2 is a subset of set1? Write a Python program to achieve this."""

set1 = {1, 2, 3, 4}
set2 = {3, 4}
result = set2.issubset(set1)
print( result)

"""Question 15: Given a set set1 = {1, 2, 3, 4, 5}, how can you convert it into a list? Write a Python program to achieve this."""

set1 = {1, 2, 3, 4, 5}
list1 = list(set1)
print("List:", list1)

"""Question 16: Suppose you have a list my_list = [10, 20, 30, 40, 50, 10, 20], how can you remove duplicates and convert it into a set? Write a Python program to achieve this."""

my_list = [10, 20, 30, 40, 50, 10, 20]
unique_set = set(my_list)
print("Set without duplicates:", unique_set)

"""Question 17: Given two sets set1 = {1, 2, 3} and set2 = {3, 4, 5}, how can you check if they are disjoint? Write a Python program to achieve this."""

set1 = {1, 2, 3}
set2 = {3, 4, 5}
result = set1.isdisjoint(set2)
print(result)

"""Question 18: Suppose you have a set my_set = {10, 20, 30}, how can you iterate over its elements and print them? Write a Python program to achieve this."""

my_set = {10, 20, 30}
for i in my_set:
    print(i)

"""Question 19: Given a set my_set = {10, 20, 30, 40, 50}, how can you find the minimum and maximum values? Write a Python program to achieve this.

"""

my_set = {10, 20, 30, 40, 50}
minimum = min(my_set)
maximum = max(my_set)
print("Minimum value:", minimum)
print("Maximum value:", maximum)

"""Question 20: Suppose you have two sets set1 = {1, 2, 3} and set2 = {4, 5, 6}, how can you merge them into a single set? Write a Python program to achieve this."""

set1 = {1, 2, 3}
set2 = {4, 5, 6}
result = set1.union(set2)
print("Merged set:", result)