# -*- coding: utf-8 -*-
"""Lab4Dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPT5F3OEME_BxGEXifi4vW3Z-_Gnvl6_

Question 1: Given a dictionary my_dict = {'a': 10, 'b': 20, 'c': 30}, how can you access the value associated with key 'b'? Write a Python program to achieve this.
"""

my_dict = {'a': 10, 'b': 20, 'c': 30}
value = my_dict['b']
print("Value of key 'b':", value)

"""Question 2: Suppose you have a dictionary my_dict = {'name': 'John', 'age': 25, 'city': 'New York'}, how can you update the value of 'age' to 30? Write a Python program to achieve this."""

my_dict = {'name': 'John', 'age': 25, 'city': 'New York'}
my_dict['age'] = 30
print(my_dict)

"""Question 3: Given a dictionary my_dict = {'a': 10, 'b': 20, 'c': 30}, how can you remove the key 'b'? Write a Python program to achieve this."""

my_dict = {'a': 10, 'b': 20, 'c': 30}
del my_dict['b']
print(my_dict)

"""Question 4: Suppose you have a dictionary my_dict = {'name': 'Alice', 'age': 30}, how can you add a new key-value pair 'city': 'London'? Write a Python program to achieve this."""

my_dict = {'name': 'Alice', 'age': 30}
my_dict['city'] = 'London'
print(my_dict)

"""Question 4: Suppose you have a dictionary my_dict = {'name': 'Alice', 'age': 30}, how can you add a new key-value pair 'city': 'London'? Write a Python program to achieve this."""

my_dict = {'name': 'Alice', 'age': 30}
my_dict['city'] = 'London'
print(my_dict)

"""Question 5: Given a dictionary my_dict = {'x': 1, 'y': 2, 'z': 3}, how can you get a list of all keys? Write a Python program to achieve this."""

my_dict = {'x': 1, 'y': 2, 'z': 3}
keys_list = list(my_dict.keys())
print("List of keys:", keys_list)

"""Question 6: Suppose you have a dictionary my_dict = {'x': 1, 'y': 2, 'z': 3}, how can you get a list of all values? Write a Python program to achieve this."""

my_dict = {'x': 1, 'y': 2, 'z': 3}
values_list = list(my_dict.values())
print("List of values:", values_list)

"""Question 7: Given a dictionary my_dict = {'a': 10, 'b': 20, 'c': 30}, how can you check if key 'b' exists? Write a Python program to achieve this."""

my_dict = {'a': 10, 'b': 20, 'c': 30}
if 'b' in my_dict:
    print("Key 'b' exists in the dictionary")
else:
    print("Key 'b' does not exist")

"""Question 8: Suppose you have a dictionary my_dict = {'a': 10, 'b': 20, 'c': 30}, how can you iterate over its key-value pairs? Write a Python program to achieve this."""

my_dict = {'a': 10, 'b': 20, 'c': 30}
for key, value in my_dict.items():
    print(key, ":", value)

"""Question 9: Given a dictionary my_dict = {'x': 1, 'y': 2, 'z': 3}, how can you clear all elements from the dictionary? Write a Python program to achieve this."""

my_dict = {'x': 1, 'y': 2, 'z': 3}
my_dict.clear()
print(my_dict)

"""Question 10: Suppose you have a dictionary my_dict = {'name': 'Alice', 'age': 30}, how can you find its length? Write a Python program to achieve this."""

my_dict = {'name': 'Alice', 'age': 30}
length = len(my_dict)
print("Length of dictionary:", length)

"""Question 11: Given two dictionaries dict1 = {'a': 1, 'b': 2} and dict2 = {'c': 3, 'd': 4}, how can you merge them? Write a Python program to achieve this."""

dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
dict1.update(dict2)
print("Merged dictionary:", dict1)

"""Question 12: Suppose you have a dictionary my_dict = {'name': 'John', 'age': 25}, how can you copy it to another dictionary? Write a Python program to achieve this."""

my_dict = {'name': 'John', 'age': 25}
new_dict = my_dict.copy()
print("Original Dictionary:", my_dict)
print("Copied Dictionary:", new_dict)

"""Question 13: Given a dictionary my_dict = {'a': 10, 'b': 20, 'c': 30}, how can you get a default value when accessing a missing key? Write a Python program to achieve this."""

my_dict = {'a': 10, 'b': 20, 'c': 30}
value = my_dict.get('d', 0)
print("Value:", value)

"""Question 14: Suppose you have a dictionary my_dict = {'name': 'Alice', 'age': 30}, how can you convert it into a list of tuples? Write a Python program to achieve this."""

my_dict = {'name': 'Alice', 'age': 30}
result = list(my_dict.items())
print("List of tuples:", result)

"""Question 15: Given a dictionary my_dict = {'a': 10, 'b': 20, 'c': 30}, how can you sort it by keys? Write a Python program to achieve this."""

my_dict = {'a': 10, 'b': 20, 'c': 30}
sorted_dict = dict(sorted(my_dict.items()))
print("Sorted dictionary:", sorted_dict)

"""Question 16: Suppose you have a dictionary my_dict = {'name': 'Alice', 'age': 30}, how can you delete the 'age' key using the pop() method? Write a Python program to achieve this."""

my_dict = {'name': 'Alice', 'age': 30}
my_dict.pop('age')
print(my_dict)

"""Question 17: Given a dictionary my_dict = {'x': 10, 'y': 20}, how can you check if it is empty? Write a Python program to achieve this."""

my_dict = {'x': 10, 'y': 20}
if not my_dict:
    print("Dictionary is empty")
else:
    print("Dictionary is not empty")

"""Question 18: Suppose you have a dictionary my_dict = {'a': 10, 'b': 20}, how can you update it with another dictionary {'c': 30, 'd': 40}? Write a Python program to achieve this."""

my_dict = {'a': 10, 'b': 20}
new_dict = {'c': 30, 'd': 40}
my_dict.update(new_dict)
print("Updated dictionary:", my_dict)

"""Question 19: Given a dictionary my_dict = {'apple': 3, 'banana': 5}, how can you get the key associated with the maximum value? Write a Python program to achieve this."""

my_dict = {'apple': 3, 'banana': 5}
max_key = max(my_dict, key=my_dict.get)
print("Key with maximum value:", max_key)

"""Question 20: Suppose you have a dictionary my_dict = {'a': 1, 'b': 2, 'c': 3}, how can you reverse its key-value pairs? Write a Python program to achieve this."""

my_dict = {'a': 1, 'b': 2, 'c': 3}
reversed_dict = {value: key for key, value in my_dict.items()}
print("Reversed dictionary:", reversed_dict)